### ISSUE TITLE
cannot import name 'DanMuClient'

### ISSUE THREAD

**Issue by applemin** [littlecodersh/danmu#17]
Traceback (most recent call last):
  File "D:/Users/yidian/PycharmProjects/trans/danmu.py", line 3, in <module>
    from danmu import DanMuClient;
  File "D:\Users\yidian\PycharmProjects\trans\danmu.py", line 3, in <module>
    from danmu import DanMuClient;
ImportError: cannot import name 'DanMuClient'

**Comment by laoyuan** [comment]
我也抱这个错，说找不到 DanMuClient

**Comment by huhudev-git** [comment]
你把你的文件名danmu改一下名就行了

**Comment by losthanKKK** [comment]
@huhugiter 把danmu改成什么名字啊

**Comment by Wangpeiyi9979** [comment]
求解决。。
