### ISSUE TITLE
功能与意见反馈，报bug可以另开issue

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/danmu#2]
这里不回答python的基础问题，只做意见收集用途。
所有意见我都会及时回复的~
报bug记得另开issue。

**Comment by kdashl** [comment]
ImportError: cannot import name DanMuClient

**Comment by ma125125t** [comment]
Hello，类似 http://www.douyu.com/cms/zt/lpl.html#a 大型活动（LPL，TI）无法读取弹幕

**Comment by littlecodersh** [comment]
@ma125125t 收到，非常感谢！下一版本中我会更新该问题。

**Comment by Ldream** [comment]
doc 中的Simple uses中content['NickName']这个地方 是不是应该改为 msg['NickName']?

**Comment by littlecodersh** [comment]
@Ldream 是的，我疏忽了！

**Comment by qianhaoqi** [comment]
你好，感谢开发如此方便的package，请问有没有计划加入龙珠TV平台呢？

**Comment by littlecodersh** [comment]
@qianhaoqi 之后有空的话我再加，你如果有研究也可以尝试着自己加一下

**Comment by Chyroc** [comment]
如果我想获取最热门的5个直播间（`http://capi.douyucdn.cn/api/v1/live?limit=5&offset=0`这个api可以获取）的弹幕，现在的问题是我可以每半个小时更新一次直播间列表，但是怎么把正在运行的程序停下来，然后换成最新的直播间列表？

**Comment by littlecodersh** [comment]
@Chyroc dmc.stop()就可以了

**Comment by Chyroc** [comment]
那怎么同时启动五个房间的弹幕

**Comment by littlecodersh** [comment]
@Chyroc 就是一样的操作开五个就可以了，我这两天挺空的，你有事都可以q叫我

**Comment by Chyroc** [comment]
弹幕的发送者昵称可以获取，那他的等级等信息可以拿到吗，还是没有分析

**Comment by littlecodersh** [comment]
@Chyroc 可以的，你可以查看一下数据包，虽然每个平台的键名不一样但是都是有的。

**Comment by bonanyuan** [comment]
我尝试了拿threading写多线程同时爬多个频道，但是不管怎么样都只能爬一个频道。大概是什么原因

**Comment by littlecodersh** [comment]
@bonanyuan 是我这里的问题，已经在新的版本（1.0.4）中修复。

**Comment by bonanyuan** [comment]
multiprocessing可以开到600频道左右，Macbook Pro 13，8GB，IO 200kb/s
拿tornado的concurrent试下？还是改init，使一个一个线程监听多个频道？

**Comment by maxdance** [comment]
请问直播间没有开播如何才能获取弹幕呢？

**Comment by maxdance** [comment]
请问有彩色弹幕的标识吗？

**Comment by al123xiaaaa** [comment]
例子中的礼物方法会报错
`@dmc.gift
def gift_fn(msg):
    pp('[%s] sent a gift!' % content['NickName'])`
content没有定义
是不是应该把content改成msg?

**Comment by littlecodersh** [comment]
@al123xiaaaa 已更新，多谢

**Comment by xytlearn** [comment]
房管的问题：“other message received ”

优点：爬取速度比直播首页的快不少

**Comment by Sofronio** [comment]
请问怎么输出礼物内容呢？

**Comment by guoguodaren787** [comment]
Traceback (most recent call last):

  File "<ipython-input-17-32357a00acd4>", line 1, in <module>
    runfile('C:/Users/guoguo/danmu66.py', wdir='C:/Users/guoguo')

  File "D:\software\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\software\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/guoguo/danmu66.py", line 30, in <module>
    dmc.start(blockThread = True)

  File "D:\software\Anaconda3\lib\site-packages\danmu\__init__.py", line 77, in start
    _start()

  File "D:\software\Anaconda3\lib\site-packages\danmu\__init__.py", line 67, in _start
    fn = self.__functionDict.get(msg['MsgType'],

KeyError: 'MsgType'

斗鱼的网页都是这样是说明原因呢？

**Comment by guoguodaren787** [comment]
Traceback (most recent call last):

  File "<ipython-input-17-32357a00acd4>", line 1, in <module>
    runfile('C:/Users/guoguo/danmu66.py', wdir='C:/Users/guoguo')

  File "D:\software\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\software\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/guoguo/danmu66.py", line 30, in <module>
    dmc.start(blockThread = True)

  File "D:\software\Anaconda3\lib\site-packages\danmu\__init__.py", line 77, in start
    _start()

  File "D:\software\Anaconda3\lib\site-packages\danmu\__init__.py", line 67, in _start
    fn = self.__functionDict.get(msg['MsgType'],

KeyError: 'MsgType'
斗鱼的网页都是这样是什么原因呢？

**Comment by csi0n** [comment]
请问，有没有打算做弹幕发送的接口？

**Comment by subtank** [comment]
房管问题：禁言记录怎么做啊？

**Comment by yutiansut** [comment]
调用api的数据 怎么可能当房管..又没有登录..

**Comment by subtank** [comment]
建议给一个房管批量禁言功能啊，设置关键词秒禁言那种。最近被炸房广告整的有点烦

**Comment by find0day** [comment]
现在 douyu ， zhanqi 的 url 都改成了 https 的方式，这里可能需要判断一下？
```python
if 'http://' == url[:7]:
    self.__url = url
else:
    self.__url = 'http://' + url
```
会导致 url 被拼成这样： http://https://www.douyu.com/32892

**Comment by haigendong** [comment]
我在chrome调试里看了虎牙是websocket传输的弹幕，但是是有好几个websocket连接，没搞明白

**Comment by subtank** [comment]
老铁主播下播以后的聊天记录能不能记录下来啊

**Comment by yusri0710** [comment]
发现有一部分全民直播带全民号的链接对不上分享链接了。比如：全民号:15673177
直播网址是：http://www.quanmin.tv/15673177
分享链接是：http://www.quanmin.tv/task/share?from=_a69ba1ba7cabda50f124a644e9742d95_1578797926
程序里用全民号来dmc = DanMuClient('https://www.quanmin.tv/15673177')就不行了，
程序里要用分享链接里的id来dmc = DanMuClient('https://www.quanmin.tv/1578797926')就可以。
大神要不要更新一下。

**Comment by qingyuj** [comment]
您好，请问弹幕API接口（http://open.douyucdn.cn/api/RoomApi/room/）我在页面怎么找不到，应该去哪里寻找呢？谢谢！！！

**Comment by lki2019** [comment]
您好，请问可以增加一个保存弹幕的功能么，斗鱼直播
比如连接上了123房间
打开到关闭过程里的所有弹幕发言内容都可以自动保存下来！

**Comment by yutiansut** [comment]
@lki2019 这个打个log或者存个txt都可以啊 这种没必要放框架的

**Comment by lki2019** [comment]
@yutiansut 额，好吧，自动保存方便啊
对了 增加用户等级显示和是手机用户还是电脑用户标记！手机用户最前面就显示手机

对了请问有直播间房管禁言查询记录的工具么？

**Comment by yutiansut** [comment]
@lki2019  阿喵,这事儿你得问作者啦 手动帮你 @littlecodersh

**Comment by lki2019** [comment]
礼物信息只显示飞机和火箭就好了，用户送出了1个火箭或者一个飞机


@dmc.danmu
def danmu_fn(msg):
    pp('[%s] %s' % (msg['NickName'], msg['Content']))


我把另外2个类型删除了 也看不到是刷了什么礼物，滚屏滚的影响看弹幕

如果只显示飞机和火箭我觉得这样还是不错的

**Comment by yutiansut** [comment]
@lki2019 礼物不需要太贵,只要香榭的落叶~~

**Comment by lki2019** [comment]
作者好像好久没露面了a 

找了好几个看弹幕的工具 还是这个作者的好点，

**Comment by lki2019** [comment]
其实我觉得最主要的功能这样：

弹幕输出格式：【电脑or手机用户】【用户等级】【昵称】内容

礼物信息只显示飞机和火箭 这2两个礼物的赠送信息

**Comment by subtank** [comment]
@yutiansut 求大佬帮忙看下最近弹幕记录器为啥啥显示都没得了。。。换了战旗，熊猫，斗鱼都没有显示。。。

**Comment by laoyuan** [comment]
能否添加 斗鱼观众进入直播间 的提示？

**Comment by xshwy** [comment]
请教一下，斗鱼平台，直播间没开播的时候，如何获取弹幕呢，现在没开播的时候不会获取弹幕呢。谢谢~

**Comment by budongjimolin** [comment]
现在熊猫tv的用不了了呀？

**Comment by subtank** [comment]
最近熊猫的好像是爆炸了。

**Comment by easeliu** [comment]
请问一下，用这个开源包可以获取优酷等视频平台上的弹幕吗

**Comment by riverlight** [comment]
淘宝直播能支持吗？

**Comment by Lunachen777** [comment]
请问一下～
第一，我想获得房间弹幕或者其他信息的产生时间，要怎么做呢？
第二，我修改了代码，def danmu_fn(msg): print('[%s] chat information' % msg)，借此获得了所有数据，但发现其中少了几个数据，包括chtin进入房间时间戳，chtout，离开房间时间戳等），这是为什么呢？

**Comment by xiaoweizbc** [comment]
https://www.douyu.com/chenyifaer 这个好像不行，能否看一下什么原因

**Comment by eleeeeeee** [comment]
火猫tv的弹幕失效了  请问能看看吗?

**Comment by pymyworld** [comment]
b站火猫貌似都失效了，大神还更新吗？

**Comment by pymyworld** [comment]
跪求大佬更新火猫

**Comment by fubendong** [comment]
淘宝现在还支持么？H5弹幕没有了。只有客户端有弹幕~

**Comment by songzi1111** [comment]
大佬试试网易cc？
