### ISSUE TITLE
斗鱼bug

### ISSUE THREAD

**Issue by hifuck** [littlecodersh/danmu#8]
获取弹幕的时候,如果有用户发送礼物会报错

**Comment by littlecodersh** [comment]
@hifuck 把报错信息发我看下

**Comment by hifuck** [comment]
Traceback (most recent call last):
  File "C:\Users\fuck\AppData\Local\Programs\Python\Python35\lib\site-packages\danmu\__init__.py", line 68, in _start
    fn(msg)
  File "D:/python/1.py", line 23, in gift_fn
    pp('[%s] sent a gift!' % content['NickName'])
NameError: name 'content' is not defined

**Comment by littlecodersh** [comment]
@hifuck 
```python
pp('[%s] sent a gift!' % msg['NickName'])
```

**Comment by gargett** [comment]
@hifuck  你好~我在你的主页找不到你的联系方式，请联系一下我，我有事要跟你沟通一下。麻烦了。306860482@qq.com
